POSTGRESQL_DBNAME = "new_deploy"
POSTGRESQL_HOST = 'localhost'
POSTGRESQL_PORT = '5432'
POSTGRESQL_USERNAME = 'postgres'
POSTGRESQL_PASSWORD = 'postgres'
POSTGRESQL_ECHO_MODE = False

PATH_TO_CONFIGS = ""
SLACK_URL = "https://hooks.slack.com/services/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"

FRONTEND_SETTINGS_KEYS = (
    "APP.AVIARY.apiKey",
    "APP.FILES_TYPES.documents.url",
    "APP.FILES_TYPES.images.updateImageUrl",
    "APP.FILES_TYPES.images.url",
    "APP.GA_KEY",
    "APP.GTM_ENABLED",
    "APP.GTM_KEY",
    "APP.GTM_TRACK_ERRORS",
    "APP.GTM_TRACK_EVENTS",
    "APP.GTM_TRACK_PAGE_VIEW",
    "APP.INSPECTLET_WID",
    "APP.MAP_ID",
    "APP.MAP_MARKER_ICON_URL",
    "APP.MAP_PK",
    "APP.MAP_TILES_URL",
    "APP.PRIVATE_SALES_ADDRESS",
    "APP.ROLLBAL_ENABLED",
    "APP.SIGN_IN_ADDRESS",
    "APP.SIGN_OUT_ADDRESS",
    "APP.SOCKET_ADDRESS",
    "APP.SPEED_OF_ME_ACCOUNT",
    "APP.SPEED_OF_ME_DOMAIN",
    "APP.SPEED_OF_ME_MIN_SPEED",
    "APP.SPEED_OF_ME_TIME",
    "APP.TERMS_AND_CONDITIONS_ADDRESS",
    "APP.TRANSLATIONS_ADDRESS",
    "APP.saveFileUrlsUrl",
    "APP.FILES_TYPES.contacts.url",
    "EMBER_LOG_VERSION",
    "ENABLE_SOURCEMAPS",
    "MINIFY_CSS",
    "MINIFY_JS",
    ("APP.COOKIES_PREFIX", "COOKIES_PREFIX"),
    ("APP.ROLLBAR_ENV", "ROLLBAR_ENV"),
    ("APP.ROLLBAR_KEY", "ROLLBAR_KEY"),
    "ember-cli-mirage.enabled",
    "APP.API_HOST",
    "APP.GAVEL_ADDRESS",
    "APP.SUPPORT_ADDRESS",
    "APP.PARTNER_CONFIGS_BUCKET",
    "APP.RECURLY_PUBLIC_KEY",
    ("APP.DEBUG", "DEBUG"),
)


PRIVATE_SALES_SETTINGS_KEYS = (
    "APP.SIGN_OUT_ADDRESS",
    "APP.TRANSLATIONS_ADDRESS",
    "APP.SOCKET_ADDRESS",
    "APP.FILES_TYPES.documents.url",
    "APP.TRANSLATIONS_ADDRESS",
    "APP.API_HOST",
    "MINIFY_CSS",
    "MINIFY_JS",
)

AUTH_SETTINGS_KEYS = (
    "APP.RECURLY_MAX_PLANS_COUNT",
    "APP.APP_ADDRESS",
    "APP.SIGN_UP_DATA_IMPORT_VALIDATE_URL",
    "APP.SIGN_UP_DATA_IMPORT_STATUS",
    "APP.FORGOT_PASSWORD_URL",
    "APP.GA_KEY",
    "APP.GTM_ENABLED",
    "APP.GTM_KEY",
    "APP.GTM_TRACK_ERRORS",
    "APP.GTM_TRACK_EVENTS",
    "APP.GTM_TRACK_PAGE_VIEW",
    "APP.INSPECTLET_WID",
    "APP.RECURLY_PLANS",
    "APP.RECURLY_PUBLIC_KEY",
    "APP.RESET_PASSWORD_URL",
    "APP.SIGN_IN_URL",
    "APP.SIGN_OUT_URL",
    "APP.SIGN_UP_BY_EMAIL_URL",
    "APP.SIGN_UP_DATA_IMPORT_STATUS",
    "APP.SIGN_UP_DATA_IMPORT_VALIDATE_URL",
    "APP.SIGN_UP_URL",
    "APP.SIGN_UP_VALIDATE_URL",
    "APP.SOCKET_ADDRESS",
    "APP.API_HOST",
    "APP.PARTNER_CONFIGS_BUCKET",
    "ENABLE_SOURCEMAPS",
    "MINIFY_CSS",
    "MINIFY_JS",
    ("APP.COOKIES_PREFIX", "COOKIES_PREFIX"),
    ("APP.ROLLBAR_ENV", "ROLLBAR_ENV"),
    ("APP.ROLLBAR_KEY", "ROLLBAR_KEY"),
    "APP.OAUTH_GRANT_URL",
    "APP.TRANSLATIONS_ADDRESS",
)

APPS_SETTINGS_MAPPING = {
    "frontend": FRONTEND_SETTINGS_KEYS,
    "auth": AUTH_SETTINGS_KEYS,
    "pvr": PRIVATE_SALES_SETTINGS_KEYS
}


UPPER_TO_LOWER_SETTINGS_MAPPINGS = {
    "DEBUG": "debug",
    "ROLLBAR_ENV": "rollbar_env",
    "ROLLBAR_KEY": "rollbar_key",
    "COOKIES_PREFIX": "cookies_prefix",
    "APP.AVIARY.apiKey": "aviary_key",
    "APP.FILES_TYPES.documents.url": ("img", "app", lambda x, y: "https://{}/document/?token={}".format(x, '{{TOKEN}}') if y == "pvr" else "https://{}/document/".format(x)),
    "APP.FILES_TYPES.images.updateImageUrl": ("img", lambda x: "https://{}/image_update".format(x)),
    "APP.FILES_TYPES.images.url": ("img", lambda x: "https://{}/image/".format(x)),
    "APP.GA_KEY": "ga_key",
    "APP.GTM_ENABLED": "gtm_enabled",
    "APP.GTM_KEY": "gtm_key",
    "APP.GTM_TRACK_ERRORS": "gtm_track_errors",
    "APP.GTM_TRACK_EVENTS": "gtm_track_events",
    "APP.GTM_TRACK_PAGE_VIEW": "gtm_track_page_view",
    "APP.INSPECTLET_WID": "inspectlet_id",
    "APP.MAP_ID": "mapbox_id",
    "APP.MAP_PK": "mapbox_key",
    "APP.PRIVATE_SALES_ADDRESS": ("pvr", lambda x: "https://{}".format(x)),
    "APP.ROLLBAL_ENABLED": "log_to_rollbar",
    "APP.SIGN_IN_ADDRESS": ("auth", "app", lambda x, y : "https://{}/sign-in?app=gavel".format(x) if y == "gavel" else "https://{}/sign-in".format(x)),
    "APP.SIGN_OUT_ADDRESS": ("auth", lambda x: "https://{}/sign-out".format(x)),
    "APP.SOCKET_ADDRESS": ("api", lambda x: "https://{}".format(x)),
    "APP.SPEED_OF_ME_ACCOUNT": "speed_of_me_account",
    "APP.SPEED_OF_ME_DOMAIN": "speed_of_me_domain",
    "APP.SPEED_OF_ME_MIN_SPEED": "speed_of_me_min_speed",
    "APP.SPEED_OF_ME_TIME": "speed_of_me_time",
    "APP.TERMS_AND_CONDITIONS_ADDRESS": "terms_and_condition_url",
    "APP.TRANSLATIONS_ADDRESS": ("api", "translations_version", lambda x, y: "https://{}/translations/{}/".format(x, y)),
    "APP.saveFileUrlsUrl": ("api", lambda x: "https://{}/contact-import".format(x)),
    "APP.FILES_TYPES.contacts.url": ("img", lambda x: "https://{}/document".format(x)),
    "EMBER_LOG_VERSION": "debug",
    "ENABLE_SOURCEMAPS": "debug",
    "MINIFY_CSS": "minify_css",
    "MINIFY_JS": "minify_js",
    "APP.MAP_MARKER_ICON_URL": "map_marker_icon_url",
    "APP.MAP_TILES_URL": "map_titles_url",
    "ember-cli-mirage.enabled": "ember_cli_mirage",
    "APP.API_HOST": ("api_v6", "aws_api_gateway_version", "gavel_domain_name", "domain_name", "app",
                     lambda x, y, n, c, z: "https://{}.{}".format(n, c) if z == "gavel" else {
                         "frontend": "https://{}/{}",
                         "admin_tool": "{}/{}",
                         "auth": "https://{}/{}",
                         "pvr": "https://{}/{}",
                     }.get(z).format(x, y)),
    "APP.ES_API_HOST": ("gavel_domain_name", "domain_name", "aws_api_gateway_version", lambda x, y, z: "{}.{}/{}/gavel".format(x, y, z)),
    "APP.RECURLY_MAX_PLANS_COUNT": "recurly_max_plans_count",
    "APP.APP_ADDRESS": ("frontend", lambda x: "https://{}".format(x)),
    "APP.SIGN_UP_DATA_IMPORT_VALIDATE_URL": ("api", lambda x: "https://{}/activate_account/".format(x)),
    "APP.SIGN_UP_DATA_IMPORT_STATUS": ("api", lambda x: "https://{}/get_migration_status/".format(x)),
    "APP.FORGOT_PASSWORD_URL": ("api", lambda x: "https://{}/forgot_password/".format(x)),
    "APP.RECURLY_PLANS": "recurly_plans",
    "APP.RECURLY_PUBLIC_KEY": "recurly_public_key",
    "APP.RESET_PASSWORD_URL": ("api", lambda x: "https://{}/reset_password/".format(x)),
    "APP.SIGN_IN_URL": ("api", lambda x: "https://{}/signin/".format(x)),
    "APP.SIGN_OUT_URL": ("api", lambda x: "https://{}/signout/".format(x)),
    "APP.SIGN_UP_BY_EMAIL_URL": ("api", lambda x: "https://{}/signup_by_invite/".format(x)),
    "APP.SIGN_UP_URL": ("api", lambda x: "https://{}/signup/".format(x)),
    "APP.SIGN_UP_VALIDATE_URL": ("api", lambda x: "https://{}/validate_signup/".format(x)),
    "APP.ROLLBAR_KEY": "rollbar_key",
    "IMAGE_PROCESSING_DOMAIN": ("img", lambda x: "https://{}".format(x)),
    "APP.SUPPORT_ADDRESS": "support_address",
    "APP.PARTNER_CONFIGS_BUCKET": "partner_configs_bucket",
}

AWS_S3_KEYS = (
    "aws_s3_key",
    "aws_s3_secret_key",
    "aws_s3_region",
)


SSL_CERT_TEXT = """
-----BEGIN CERTIFICATE-----
MIIE8zCCA9ugAwIBAgIQGfwXF/tjErA57K2133hukjANBgkqhkiG9w0BAQsFADBG
MQswCQYDVQQGEwJVUzEWMBQGA1UEChMNR2VvVHJ1c3QgSW5jLjEfMB0GA1UEAxMW
R2VvVHJ1c3QgU0hBMjU2IFNTTCBDQTAeFw0xNDEwMTYwMDAwMDBaFw0xNjEwMTQy
MzU5NTlaMGkxCzAJBgNVBAYTAlVTMREwDwYDVQQIDAhOZXcgWW9yazERMA8GA1UE
BwwITmV3IFlvcmsxGDAWBgNVBAoMD0NvbGxlY3RyaXVtIExMQzEaMBgGA1UEAwwR
Ki5jb2xsZWN0cml1bS5jb20wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB
AQDNagDb/NTSYp9rhEFKwp+4RbsBbFaqrxC4nyyIu/7qKLjK6aPe7qGyBQI56z43
J292m2EB0wtd/n3Adj2RPfg6ycgll1xeACXWlKwwJDhlL9/8ORtkeGrvcx3ZV9xD
cCcTVUpGYOgiXdEj1n/qJ6b6a/bwh11uswDQb2dLuecWxYW2IvFKamUVBhrqDkU2
j78Tvk2pHWT3ebAGJ3wf8Jcyw8Dl06Vgdo50DquTVrxkIj9rLM2/bE+feVHdtdOO
ExPuj7VDlxXPrxzSGCznY1EdoDqnkvMr/S6i5qJBy6RSQt1o+qhlAn2zxk6K3UB0
7yaEXG6OI4Ntl6NVwpWu5LAjAgMBAAGjggG4MIIBtDAtBgNVHREEJjAkghEqLmNv
bGxlY3RyaXVtLmNvbYIPY29sbGVjdHJpdW0uY29tMAkGA1UdEwQCMAAwDgYDVR0P
AQH/BAQDAgWgMCsGA1UdHwQkMCIwIKAeoByGGmh0dHA6Ly9nai5zeW1jYi5jb20v
Z2ouY3JsMIGhBgNVHSAEgZkwgZYwgZMGCmCGSAGG+EUBBzYwgYQwPwYIKwYBBQUH
AgEWM2h0dHBzOi8vd3d3Lmdlb3RydXN0LmNvbS9yZXNvdXJjZXMvcmVwb3NpdG9y
eS9sZWdhbDBBBggrBgEFBQcCAjA1DDNodHRwczovL3d3dy5nZW90cnVzdC5jb20v
cmVzb3VyY2VzL3JlcG9zaXRvcnkvbGVnYWwwHQYDVR0lBBYwFAYIKwYBBQUHAwEG
CCsGAQUFBwMCMB8GA1UdIwQYMBaAFBRnju2DT9YenUAEDARGoXA0sg9yMFcGCCsG
AQUFBwEBBEswSTAfBggrBgEFBQcwAYYTaHR0cDovL2dqLnN5bWNkLmNvbTAmBggr
BgEFBQcwAoYaaHR0cDovL2dqLnN5bWNiLmNvbS9nai5jcnQwDQYJKoZIhvcNAQEL
BQADggEBAKOXUMgsUfX1qfvI5NcJxPgFPnzvoz3gXpmsMyg8q3wtGPEIeaqRQhdP
2G7ONmGDWxMAZw2s+iGbgMjLX+yh5ymo3t+4ofkEv/FaojuK2k6yN5ccggRNY/va
RFpWKy1VFY4P+ifWfzHS3BQHL+tijYKj8a9/buzU5AhF5i2gVN/217HrH3bu7bgE
BOoUf2EBlSaephm7ERC5CLRHkhYOP6fl7uds098tMWWid9/86K866ba3hh3v3Qyl
kj5VuSw4su6BDhbks/4NSwOsDk667JER+iwR9FEC9u4dxYrc37Kmp26mqRiUS8SB
NgU/vosZfGXwAaWKx/rGBoEG9qm5BZ0=
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIIExzCCA6+gAwIBAgIQQYISfRLZxrMhOUMSVmQAuDANBgkqhkiG9w0BAQsFADCB
mDELMAkGA1UEBhMCVVMxFjAUBgNVBAoTDUdlb1RydXN0IEluYy4xOTA3BgNVBAsT
MChjKSAyMDA4IEdlb1RydXN0IEluYy4gLSBGb3IgYXV0aG9yaXplZCB1c2Ugb25s
eTE2MDQGA1UEAxMtR2VvVHJ1c3QgUHJpbWFyeSBDZXJ0aWZpY2F0aW9uIEF1dGhv
cml0eSAtIEczMB4XDTEzMDUyMzAwMDAwMFoXDTIzMDUyMjIzNTk1OVowRjELMAkG
A1UEBhMCVVMxFjAUBgNVBAoTDUdlb1RydXN0IEluYy4xHzAdBgNVBAMTFkdlb1Ry
dXN0IFNIQTI1NiBTU0wgQ0EwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB
AQDGqQtdF6V9xs8q78Zm0UIeX4N4aJGv5qeL8B1EAQoZypzUix3hoZCjwVu011tq
i/wOSR7CYin+gBU5i4EqJ7X7EqgFIgvFLPXZmN0WLztm52KiQzKsj7WFyFIGLFzA
d/pn94PoXgWNyKuhFjKK0kDshjocI6mNtQDecr2FVf4GAWBdrbPgZXOlkhSelFZv
k+6vqTowJUqOCYTvt9LV15tJzenAXmdxIqxQkEMgXaGjFYP9/Kc5vGtlSBJg/90j
szqq9J+cN1NBokeTgTMJ5SLGyBxJoW6NzIOzms3qQ/IZ0yTLqCmuUsz0CCewhOrO
J7XhNBNzklyHhirGsGg2rcsJAgMBAAGjggFcMIIBWDA7BggrBgEFBQcBAQQvMC0w
KwYIKwYBBQUHMAGGH2h0dHA6Ly9wY2EtZzMtb2NzcC5nZW90cnVzdC5jb20wEgYD
VR0TAQH/BAgwBgEB/wIBADBMBgNVHSAERTBDMEEGCmCGSAGG+EUBBzYwMzAxBggr
BgEFBQcCARYlaHR0cDovL3d3dy5nZW90cnVzdC5jb20vcmVzb3VyY2VzL2NwczA7
BgNVHR8ENDAyMDCgLqAshipodHRwOi8vY3JsLmdlb3RydXN0LmNvbS9HZW9UcnVz
dFBDQS1HMy5jcmwwDgYDVR0PAQH/BAQDAgEGMCoGA1UdEQQjMCGkHzAdMRswGQYD
VQQDExJWZXJpU2lnbk1QS0ktMi00MTYwHQYDVR0OBBYEFBRnju2DT9YenUAEDARG
oXA0sg9yMB8GA1UdIwQYMBaAFMR5yo6hTgMdHNxr2zFblD4/MH8tMA0GCSqGSIb3
DQEBCwUAA4IBAQAQEOryENYIRuLBjz42WcgrD/5N7OP4tlYxeCXUdvII3e8/zYsc
fqp//AuoI2RRs4fWCfoi+scKUejOuPYDcOAbWrmxspMREPmXBQcpbG1XJVTo+Wab
Dvvbn+6Wb2XLH9hVzjH6zwL00H9QZv8veZulwt/Wz8gVg5aEmLJG1F8TqD6nNJwF
ONrP1mmVqSaHdgHXslEPgWlGJhyZtoNY4ztYj9y0ccC5v0KcHAOe5Eao6rnBzfZb
qTyW+3mkM3Onnni5cNxydMQyyAAbye9I0/s6m/r+eppAaRzI2ig3C9OjuX6WzCso
w1Zsb+nbUrH6mvvnr7WXpiLDxaiTsQDJB7J9
-----END CERTIFICATE-----

"""

#.collectriumdev.com
SSL_CERT_DEV_TEXT = """
-----BEGIN CERTIFICATE-----
MIIFZDCCBEygAwIBAgIRALWt+NR7IsMFMcmQhDSSWhMwDQYJKoZIhvcNAQELBQAw
gZAxCzAJBgNVBAYTAkdCMRswGQYDVQQIExJHcmVhdGVyIE1hbmNoZXN0ZXIxEDAO
BgNVBAcTB1NhbGZvcmQxGjAYBgNVBAoTEUNPTU9ETyBDQSBMaW1pdGVkMTYwNAYD
VQQDEy1DT01PRE8gUlNBIERvbWFpbiBWYWxpZGF0aW9uIFNlY3VyZSBTZXJ2ZXIg
Q0EwHhcNMTUwNzIzMDAwMDAwWhcNMTYwNzIyMjM1OTU5WjBhMSEwHwYDVQQLExhE
b21haW4gQ29udHJvbCBWYWxpZGF0ZWQxHTAbBgNVBAsTFFBvc2l0aXZlU1NMIFdp
bGRjYXJkMR0wGwYDVQQDDBQqLmNvbGxlY3RyaXVtZGV2LmNvbTCCASIwDQYJKoZI
hvcNAQEBBQADggEPADCCAQoCggEBAMJPbswodQ3HASiRF5+o3di8PROSSFMFMb/C
8nlKyCoqvpZky4uZxlz55z1qbTAzwIRCSN7jWFyecKs3uhP2KiNkp+bOufOQL9kW
xrdi2hoXtlX/CBZ3AXZXPXeofjQsXgOHslKC1sJVZoOV+WR/BmiHIIFkzVPq7AWM
2/XoN6KMaqRAaF0u5maZ8kRsR2y/ByWpkTYaXvwXrJ5vqx0nzhvVPV+/GAGPZz6K
f1LAMoeWeZ3iiUXW77Lbln3tx6VAlCy01pcA14CYh7/MRlPCEAfWT7qpD+YrRABy
yDfNB+KqjCfSoEz8wMQ3MFcxsh7nY5xs//JCWYITXzJ2Azoht10CAwEAAaOCAeUw
ggHhMB8GA1UdIwQYMBaAFJCvajqUWgvYkOoSVnPfQ7Q6KNrnMB0GA1UdDgQWBBT9
gho6jJLAS0kh+XlWAAeLLo5d1TAOBgNVHQ8BAf8EBAMCBaAwDAYDVR0TAQH/BAIw
ADAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwTwYDVR0gBEgwRjA6Bgsr
BgEEAbIxAQICBzArMCkGCCsGAQUFBwIBFh1odHRwczovL3NlY3VyZS5jb21vZG8u
Y29tL0NQUzAIBgZngQwBAgEwVAYDVR0fBE0wSzBJoEegRYZDaHR0cDovL2NybC5j
b21vZG9jYS5jb20vQ09NT0RPUlNBRG9tYWluVmFsaWRhdGlvblNlY3VyZVNlcnZl
ckNBLmNybDCBhQYIKwYBBQUHAQEEeTB3ME8GCCsGAQUFBzAChkNodHRwOi8vY3J0
LmNvbW9kb2NhLmNvbS9DT01PRE9SU0FEb21haW5WYWxpZGF0aW9uU2VjdXJlU2Vy
dmVyQ0EuY3J0MCQGCCsGAQUFBzABhhhodHRwOi8vb2NzcC5jb21vZG9jYS5jb20w
MwYDVR0RBCwwKoIUKi5jb2xsZWN0cml1bWRldi5jb22CEmNvbGxlY3RyaXVtZGV2
LmNvbTANBgkqhkiG9w0BAQsFAAOCAQEAc9ItgvOwsF5NozqlpY48vZU8Ezjcwtmd
5MLfxIssoZ+/WATI1B91nRQk+ZKpanyqGi9+N4QiTsPS8ZWZIQSkkdM9KJpOgenc
8/70TalmFyE4ObXoT0I1GUXMYsP0ujcDDAPhzybGhNRpfMes1X7GrV2iZqo7vfYe
IeVElBzUulPZiDnDK4ptKXAQSO89Ql0O+GLgZf/Lvld6uPQzmydWy/NgxS9gx0ld
ff2+EKYCD8GqO2ExeFmV8bb5PRDzAh568V+vJ3grnAhv4/V2lCo6qQlMVQDjBhLs
PreqXIa4sIQsspBM1IWWH0+X106rGBGmfbiDn8FAxhNqyyMnbN+/yw==
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIIFdDCCBFygAwIBAgIQJ2buVutJ846r13Ci/ITeIjANBgkqhkiG9w0BAQwFADBv
MQswCQYDVQQGEwJTRTEUMBIGA1UEChMLQWRkVHJ1c3QgQUIxJjAkBgNVBAsTHUFk
ZFRydXN0IEV4dGVybmFsIFRUUCBOZXR3b3JrMSIwIAYDVQQDExlBZGRUcnVzdCBF
eHRlcm5hbCBDQSBSb290MB4XDTAwMDUzMDEwNDgzOFoXDTIwMDUzMDEwNDgzOFow
gYUxCzAJBgNVBAYTAkdCMRswGQYDVQQIExJHcmVhdGVyIE1hbmNoZXN0ZXIxEDAO
BgNVBAcTB1NhbGZvcmQxGjAYBgNVBAoTEUNPTU9ETyBDQSBMaW1pdGVkMSswKQYD
VQQDEyJDT01PRE8gUlNBIENlcnRpZmljYXRpb24gQXV0aG9yaXR5MIICIjANBgkq
hkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAkehUktIKVrGsDSTdxc9EZ3SZKzejfSNw
AHG8U9/E+ioSj0t/EFa9n3Byt2F/yUsPF6c947AEYe7/EZfH9IY+Cvo+XPmT5jR6
2RRr55yzhaCCenavcZDX7P0N+pxs+t+wgvQUfvm+xKYvT3+Zf7X8Z0NyvQwA1onr
ayzT7Y+YHBSrfuXjbvzYqOSSJNpDa2K4Vf3qwbxstovzDo2a5JtsaZn4eEgwRdWt
4Q08RWD8MpZRJ7xnw8outmvqRsfHIKCxH2XeSAi6pE6p8oNGN4Tr6MyBSENnTnIq
m1y9TBsoilwie7SrmNnu4FGDwwlGTm0+mfqVF9p8M1dBPI1R7Qu2XK8sYxrfV8g/
vOldxJuvRZnio1oktLqpVj3Pb6r/SVi+8Kj/9Lit6Tf7urj0Czr56ENCHonYhMsT
8dm74YlguIwoVqwUHZwK53Hrzw7dPamWoUi9PPevtQ0iTMARgexWO/bTouJbt7IE
IlKVgJNp6I5MZfGRAy1wdALqi2cVKWlSArvX31BqVUa/oKMoYX9w0MOiqiwhqkfO
KJwGRXa/ghgntNWutMtQ5mv0TIZxMOmm3xaG4Nj/QN370EKIf6MzOi5cHkERgWPO
GHFrK+ymircxXDpqR+DDeVnWIBqv8mqYqnK8V0rSS527EPywTEHl7R09XiidnMy/
s1Hap0flhFMCAwEAAaOB9DCB8TAfBgNVHSMEGDAWgBStvZh6NLQm9/rEJlTvA73g
JMtUGjAdBgNVHQ4EFgQUu69+Aj36pvE8hI6t7jiY7NkyMtQwDgYDVR0PAQH/BAQD
AgGGMA8GA1UdEwEB/wQFMAMBAf8wEQYDVR0gBAowCDAGBgRVHSAAMEQGA1UdHwQ9
MDswOaA3oDWGM2h0dHA6Ly9jcmwudXNlcnRydXN0LmNvbS9BZGRUcnVzdEV4dGVy
bmFsQ0FSb290LmNybDA1BggrBgEFBQcBAQQpMCcwJQYIKwYBBQUHMAGGGWh0dHA6
Ly9vY3NwLnVzZXJ0cnVzdC5jb20wDQYJKoZIhvcNAQEMBQADggEBAGS/g/FfmoXQ
zbihKVcN6Fr30ek+8nYEbvFScLsePP9NDXRqzIGCJdPDoCpdTPW6i6FtxFQJdcfj
Jw5dhHk3QBN39bSsHNA7qxcS1u80GH4r6XnTq1dFDK8o+tDb5VCViLvfhVdpfZLY
Uspzgb8c8+a4bmYRBbMelC1/kZWSWfFMzqORcUx8Rww7Cxn2obFshj5cqsQugsv5
B5a6SE2Q8pTIqXOi6wZ7I53eovNNVZ96YUWYGGjHXkBrI/V5eu+MtWuLt29G9Hvx
PUsE2JOAWVrgQSQdso8VYFhH2+9uRv0V9dlfmrPb2LjkQLPNlzmuhbsdjrzch5vR
pu/xO28QOG8=
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIIGCDCCA/CgAwIBAgIQKy5u6tl1NmwUim7bo3yMBzANBgkqhkiG9w0BAQwFADCB
hTELMAkGA1UEBhMCR0IxGzAZBgNVBAgTEkdyZWF0ZXIgTWFuY2hlc3RlcjEQMA4G
A1UEBxMHU2FsZm9yZDEaMBgGA1UEChMRQ09NT0RPIENBIExpbWl0ZWQxKzApBgNV
BAMTIkNPTU9ETyBSU0EgQ2VydGlmaWNhdGlvbiBBdXRob3JpdHkwHhcNMTQwMjEy
MDAwMDAwWhcNMjkwMjExMjM1OTU5WjCBkDELMAkGA1UEBhMCR0IxGzAZBgNVBAgT
EkdyZWF0ZXIgTWFuY2hlc3RlcjEQMA4GA1UEBxMHU2FsZm9yZDEaMBgGA1UEChMR
Q09NT0RPIENBIExpbWl0ZWQxNjA0BgNVBAMTLUNPTU9ETyBSU0EgRG9tYWluIFZh
bGlkYXRpb24gU2VjdXJlIFNlcnZlciBDQTCCASIwDQYJKoZIhvcNAQEBBQADggEP
ADCCAQoCggEBAI7CAhnhoFmk6zg1jSz9AdDTScBkxwtiBUUWOqigwAwCfx3M28Sh
bXcDow+G+eMGnD4LgYqbSRutA776S9uMIO3Vzl5ljj4Nr0zCsLdFXlIvNN5IJGS0
Qa4Al/e+Z96e0HqnU4A7fK31llVvl0cKfIWLIpeNs4TgllfQcBhglo/uLQeTnaG6
ytHNe+nEKpooIZFNb5JPJaXyejXdJtxGpdCsWTWM/06RQ1A/WZMebFEh7lgUq/51
UHg+TLAchhP6a5i84DuUHoVS3AOTJBhuyydRReZw3iVDpA3hSqXttn7IzW3uLh0n
c13cRTCAquOyQQuvvUSH2rnlG51/ruWFgqUCAwEAAaOCAWUwggFhMB8GA1UdIwQY
MBaAFLuvfgI9+qbxPISOre44mOzZMjLUMB0GA1UdDgQWBBSQr2o6lFoL2JDqElZz
30O0Oija5zAOBgNVHQ8BAf8EBAMCAYYwEgYDVR0TAQH/BAgwBgEB/wIBADAdBgNV
HSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwGwYDVR0gBBQwEjAGBgRVHSAAMAgG
BmeBDAECATBMBgNVHR8ERTBDMEGgP6A9hjtodHRwOi8vY3JsLmNvbW9kb2NhLmNv
bS9DT01PRE9SU0FDZXJ0aWZpY2F0aW9uQXV0aG9yaXR5LmNybDBxBggrBgEFBQcB
AQRlMGMwOwYIKwYBBQUHMAKGL2h0dHA6Ly9jcnQuY29tb2RvY2EuY29tL0NPTU9E
T1JTQUFkZFRydXN0Q0EuY3J0MCQGCCsGAQUFBzABhhhodHRwOi8vb2NzcC5jb21v
ZG9jYS5jb20wDQYJKoZIhvcNAQEMBQADggIBAE4rdk+SHGI2ibp3wScF9BzWRJ2p
mj6q1WZmAT7qSeaiNbz69t2Vjpk1mA42GHWx3d1Qcnyu3HeIzg/3kCDKo2cuH1Z/
e+FE6kKVxF0NAVBGFfKBiVlsit2M8RKhjTpCipj4SzR7JzsItG8kO3KdY3RYPBps
P0/HEZrIqPW1N+8QRcZs2eBelSaz662jue5/DJpmNXMyYE7l3YphLG5SEXdoltMY
dVEVABt0iN3hxzgEQyjpFv3ZBdRdRydg1vs4O2xyopT4Qhrf7W8GjEXCBgCq5Ojc
2bXhc3js9iPc0d1sjhqPpepUfJa3w/5Vjo1JXvxku88+vZbrac2/4EjxYoIQ5QxG
V/Iz2tDIY+3GH5QFlkoakdH368+PUq4NCNk+qKBR6cGHdNXJ93SrLlP7u3r7l+L4
HyaPs9Kg4DdbKDsx5Q5XLVq4rXmsXiBmGqW5prU5wfWYQ//u+aen/e7KJD2AFsQX
j4rBYKEMrltDR5FL1ZoXX/nUh8HCjLfn4g8wGTeGrODcQgPmlKidrv0PJFGUzpII
0fxQ8ANAe4hZ7Q7drNJ3gjTcBpUC2JD5Leo31Rpg0Gcg19hCC0Wvgmje3WYkN5Ap
lBlGGSW4gNfL1IYoakRwJiNiqZ+Gb7+6kHDSVneFeO/qJakXzlByjAA6quPbYzSf
+AZxAeKCINT+b72x
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIIENjCCAx6gAwIBAgIBATANBgkqhkiG9w0BAQUFADBvMQswCQYDVQQGEwJTRTEU
MBIGA1UEChMLQWRkVHJ1c3QgQUIxJjAkBgNVBAsTHUFkZFRydXN0IEV4dGVybmFs
IFRUUCBOZXR3b3JrMSIwIAYDVQQDExlBZGRUcnVzdCBFeHRlcm5hbCBDQSBSb290
MB4XDTAwMDUzMDEwNDgzOFoXDTIwMDUzMDEwNDgzOFowbzELMAkGA1UEBhMCU0Ux
FDASBgNVBAoTC0FkZFRydXN0IEFCMSYwJAYDVQQLEx1BZGRUcnVzdCBFeHRlcm5h
bCBUVFAgTmV0d29yazEiMCAGA1UEAxMZQWRkVHJ1c3QgRXh0ZXJuYWwgQ0EgUm9v
dDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALf3GjPm8gAELTngTlvt
H7xsD821+iO2zt6bETOXpClMfZOfvUq8k+0DGuOPz+VtUFrWlymUWoCwSXrbLpX9
uMq/NzgtHj6RQa1wVsfwTz/oMp50ysiQVOnGXw94nZpAPA6sYapeFI+eh6FqUNzX
mk6vBbOmcZSccbNQYArHE504B4YCqOmoaSYYkKtMsE8jqzpPhNjfzp/haW+710LX
a0Tkx63ubUFfclpxCDezeWWkWaCUN/cALw3CknLa0Dhy2xSoRcRdKn23tNbE7qzN
E0S3ySvdQwAl+mG5aWpYIxG3pzOPVnVZ9c0p10a3CitlttNCbxWyuHv77+ldU9U0
WicCAwEAAaOB3DCB2TAdBgNVHQ4EFgQUrb2YejS0Jvf6xCZU7wO94CTLVBowCwYD
VR0PBAQDAgEGMA8GA1UdEwEB/wQFMAMBAf8wgZkGA1UdIwSBkTCBjoAUrb2YejS0
Jvf6xCZU7wO94CTLVBqhc6RxMG8xCzAJBgNVBAYTAlNFMRQwEgYDVQQKEwtBZGRU
cnVzdCBBQjEmMCQGA1UECxMdQWRkVHJ1c3QgRXh0ZXJuYWwgVFRQIE5ldHdvcmsx
IjAgBgNVBAMTGUFkZFRydXN0IEV4dGVybmFsIENBIFJvb3SCAQEwDQYJKoZIhvcN
AQEFBQADggEBALCb4IUlwtYj4g+WBpKdQZic2YR5gdkeWxQHIzZlj7DYd7usQWxH
YINRsPkyPef89iYTx4AWpb9a/IfPeHmJIZriTAcKhjW88t5RxNKWt9x+Tu5w/Rw5
6wwCURQtjr0W4MHfRnXnJK3s9EK0hZNwEGe6nQY1ShjTK3rMUUKhemPR5ruhxSvC
Nr4TDea9Y355e6cJDUCrat2PisP29owaQgVR1EX1n6diIWgVIEM8med8vSTYqZEX
c4g/VhsxOBi0cQ+azcgOno4uG+GMmIPLHzHxREzGBHNJdmAPx/i9F4BrLunMTA5a
mnkPIAou1Z5jJh5VkpTYghdae9C8x49OhgQ=
-----END CERTIFICATE-----
"""

SSL_KEY_PATH = '/home/ubuntu/ssl/key.pem'
SSL_KEY_TEXT = """
-----BEGIN RSA PRIVATE KEY-----
MIIEowIBAAKCAQEAzWoA2/zU0mKfa4RBSsKfuEW7AWxWqq8QuJ8siLv+6ii4yumj
3u6hsgUCOes+NydvdpthAdMLXf59wHY9kT34OsnIJZdcXgAl1pSsMCQ4ZS/f/Dkb
ZHhq73Md2VfcQ3AnE1VKRmDoIl3RI9Z/6iem+mv28IddbrMA0G9nS7nnFsWFtiLx
SmplFQYa6g5FNo+/E75NqR1k93mwBid8H/CXMsPA5dOlYHaOdA6rk1a8ZCI/ayzN
v2xPn3lR3bXTjhMT7o+1Q5cVz68c0hgs52NRHaA6p5LzK/0uouaiQcukUkLdaPqo
ZQJ9s8ZOit1AdO8mhFxujiODbZejVcKVruSwIwIDAQABAoIBABvV/pHRHEH6TWIz
hOmNoDlHccUKml/840Yxg8Zvu2ad6BTPPn6qVc0a8qdIoqC0vl0TRz0JDWRKZV4c
Z9Fz1VyaFX5KmaC/YmFGumK3tdC4gSDb2ENwMgWK0wOt7VJSM2liSHNrFGn7zqiN
m73ua6lJ0ifcICQtK7ITNqtDYPZrxa3eggy3sofG3/MRdvl4mdm1Pdp3R6YG5yKi
sI5JS9x8KORmBItobUhDMDA+Vuo5gwtBZ/U+QxjhVFVpEk6sh6yCTjzz0mZtbYYH
G1LwEOwzI5ZFLtPNtVS43rl7hOpd8yjgTKaVCM87GzP2jogkShTyktkwIX0T5ws2
wN54H7kCgYEA8OsKPTIaxSZ0lnRXbWpotHPOhCSmgPK9dvrAXHM1oj64Kdx8Gsl+
CjxM37xBb2wcjtXg1nfGY+p6iXyQHD5gTVPF6hRy8a1OVl7LoLn+lb1v0iGLmO8/
jwghYCNhvYLdxJkbfhY/rVgmUl0zqe+nyOwrGDsv/4qNtPuxyZCGXpcCgYEA2kX5
fNvQPMIbki60cv8Kubsz+OpFxMNBptrAEu88NN2tD14BWsF9RGgroXuiG+uWCmGv
nB1aypxzzvWO/sb7uSu5UBAJYX8sK3/vbkiuGNl04A0rcHZRnDDUqsY6rH/PtSNd
wIVsYi3LcQkINUWUUs6RVRAE0eIExI0mgCgj+FUCgYEAhcDoOVt081nLRrCmzU9T
fEQDNugmLNcXi1PhsjIgZ8hMdKk9mZ2eRU5/G4QoDBVIsaBaqJds5JIMoAIw/A1B
aA0Hh1L9EeI26MrOYJiCmF3JFC+dkjXZ4q4P4ZEjNZTPTNP4KINvrOyQsg+enE06
qNk9f8F0f3pL/Fv0s8RyZVcCgYAEL71mSK0IzUxMFHs/jWa+Qznu90dZS8lxktaG
RnJoLSxJlCsAe5+UdU8I7N8iG/Wnw1Hj86gvJKsP+CPC/TwMxCrsvzH+3bqSJwUH
n3s/XMRiG76OjKZqEYGyuNSdRGJOfhwpOiXnCCvTwjGXG/uJTw74i7Mb93LR9kcb
xClUdQKBgEBbDj3OLhIJEgP3FYwXHtkidCG+DQoS28cpixJd9aOcKIxjDxxxah4t
tUKw37rbf49ggYhLI3IrUJztgQFBcCd9eyJ4pDRudMg3PKCyARyvkQYlzOvnh919
1hmFc+L4JMlrKPGZH2nR6lbewpc3r76otuA0FqQt1XRBJRkGiTLO
-----END RSA PRIVATE KEY-----
"""

#.collectriumdev.com
SSL_KEY_DEV_TEXT = """
-----BEGIN RSA PRIVATE KEY-----
MIIEpAIBAAKCAQEAwk9uzCh1DccBKJEXn6jd2Lw9E5JIUwUxv8LyeUrIKiq+lmTL
i5nGXPnnPWptMDPAhEJI3uNYXJ5wqze6E/YqI2Sn5s6585Av2RbGt2LaGhe2Vf8I
FncBdlc9d6h+NCxeA4eyUoLWwlVmg5X5ZH8GaIcggWTNU+rsBYzb9eg3ooxqpEBo
XS7mZpnyRGxHbL8HJamRNhpe/Besnm+rHSfOG9U9X78YAY9nPop/UsAyh5Z5neKJ
RdbvstuWfe3HpUCULLTWlwDXgJiHv8xGU8IQB9ZPuqkP5itEAHLIN80H4qqMJ9Kg
TPzAxDcwVzGyHudjnGz/8kJZghNfMnYDOiG3XQIDAQABAoIBAQCsnn5ytlpOtAUO
cd9Hwm/bNFcaBPFld47bqadZI5sxAqov1zmQOjsjrArG375CfSdBF9W+1L9SAJtd
L/OJ+j0zFh+nBu3hN62aMQa2MgZJ+djNCvS3aF+PLy93FuOPG/8lKa68aGm7WLzq
lxhoNASQZcL10IQsUd39jEZ4biTGrGUf951G/kJqP3E3u3hWkldSYBHkO6Ehm4CV
6JdZv+OYLMJ+oW1sZtHabXlDwyd9MGiT/ZqmqyKdQj6y1YeI9CHsRuTxq1NfTqVQ
x0p/bxyt8f3OroVn4SNEX+mWL+AfD6AmhT9zFQ05dxYoXjPYpn12D+c2CopZ4PYS
HwXGrdHhAoGBAOd6PZpKEpkVK/7uckbN2Wh9KV8fmaFobFhdiGOnw1jeB0dRadkL
Zsmy1m8LlHAFO92znV8uH7AQf8gdzDHN0ku9jUV1rI+5MsIvNdIZshkg8f6ZVAnX
CAX0xbJLHZaQlrnWXzGAAFqXdbdsDvRqiMP02tNEhdoLCAEz3WW8KBHlAoGBANbl
M+14osU9nffylBeJsiKi9pJR9jXRNRnGh1bI/yTwIjkazsek7lug7StWGxgLFI+T
RQH5DUMfrMKeE19Z7pWt+LGJzTrD6R4KRwmyUZXayKtfP/GiFHV48RYFVmWZL/zx
QnDujPxQWBF0RNtRu9hDlurwU3/Rv+In7Gs3uJgZAoGAeC/0RGQpe+qOSXOtSi4f
sC0sigNyVWhOuSL3aib1OvMtfE49U0CkQh3lUQsGK5PMHbThBUaBlX07m8A9Aa8I
feMRsvsCei2CuWih3VESNBHzFGqwQ9uugskwzP5Lgp3YZO11x9HaXS8/I9mreiTG
llhQNlnh1fDcWyN+1Q/5DjECgYBu6/gVx4MdFGUJqujODYEpZ7ymYjAYL1idaWBK
Z41rX5gKqc+6NWPjX/mLuPJbQrzmLzobfpZd42elPTr6qM0B7b7ExUBt6NnXa66n
TqfWFgwmiQ/UhbjRug+XMkIaRywB//YvnLKhOkd7Guy/2DyBsMGhm1M+UuIctkbO
QQDDYQKBgQCp5T259JRTt+gUXAq3Pd+zDWC8KjwoBVDAxxEbFfDRFUmpSxTU42Nf
wD6ZcuCKYLTBFHldIN3Ikj1RxGqEZsQcVHc22hmNZG1lxPBwKtdY9Y8KaZRIXOuX
Sz5hofez7iM/C2krafMV9mdAzgp0VC7GFX/0nnJbotR9ER5u7HxtcA==
-----END RSA PRIVATE KEY-----
"""

CF_SSL_CERT_DEV_TEXT="""
-----BEGIN CERTIFICATE-----
MIIFZDCCBEygAwIBAgIRALWt+NR7IsMFMcmQhDSSWhMwDQYJKoZIhvcNAQELBQAw
gZAxCzAJBgNVBAYTAkdCMRswGQYDVQQIExJHcmVhdGVyIE1hbmNoZXN0ZXIxEDAO
BgNVBAcTB1NhbGZvcmQxGjAYBgNVBAoTEUNPTU9ETyBDQSBMaW1pdGVkMTYwNAYD
VQQDEy1DT01PRE8gUlNBIERvbWFpbiBWYWxpZGF0aW9uIFNlY3VyZSBTZXJ2ZXIg
Q0EwHhcNMTUwNzIzMDAwMDAwWhcNMTYwNzIyMjM1OTU5WjBhMSEwHwYDVQQLExhE
b21haW4gQ29udHJvbCBWYWxpZGF0ZWQxHTAbBgNVBAsTFFBvc2l0aXZlU1NMIFdp
bGRjYXJkMR0wGwYDVQQDDBQqLmNvbGxlY3RyaXVtZGV2LmNvbTCCASIwDQYJKoZI
hvcNAQEBBQADggEPADCCAQoCggEBAMJPbswodQ3HASiRF5+o3di8PROSSFMFMb/C
8nlKyCoqvpZky4uZxlz55z1qbTAzwIRCSN7jWFyecKs3uhP2KiNkp+bOufOQL9kW
xrdi2hoXtlX/CBZ3AXZXPXeofjQsXgOHslKC1sJVZoOV+WR/BmiHIIFkzVPq7AWM
2/XoN6KMaqRAaF0u5maZ8kRsR2y/ByWpkTYaXvwXrJ5vqx0nzhvVPV+/GAGPZz6K
f1LAMoeWeZ3iiUXW77Lbln3tx6VAlCy01pcA14CYh7/MRlPCEAfWT7qpD+YrRABy
yDfNB+KqjCfSoEz8wMQ3MFcxsh7nY5xs//JCWYITXzJ2Azoht10CAwEAAaOCAeUw
ggHhMB8GA1UdIwQYMBaAFJCvajqUWgvYkOoSVnPfQ7Q6KNrnMB0GA1UdDgQWBBT9
gho6jJLAS0kh+XlWAAeLLo5d1TAOBgNVHQ8BAf8EBAMCBaAwDAYDVR0TAQH/BAIw
ADAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwTwYDVR0gBEgwRjA6Bgsr
BgEEAbIxAQICBzArMCkGCCsGAQUFBwIBFh1odHRwczovL3NlY3VyZS5jb21vZG8u
Y29tL0NQUzAIBgZngQwBAgEwVAYDVR0fBE0wSzBJoEegRYZDaHR0cDovL2NybC5j
b21vZG9jYS5jb20vQ09NT0RPUlNBRG9tYWluVmFsaWRhdGlvblNlY3VyZVNlcnZl
ckNBLmNybDCBhQYIKwYBBQUHAQEEeTB3ME8GCCsGAQUFBzAChkNodHRwOi8vY3J0
LmNvbW9kb2NhLmNvbS9DT01PRE9SU0FEb21haW5WYWxpZGF0aW9uU2VjdXJlU2Vy
dmVyQ0EuY3J0MCQGCCsGAQUFBzABhhhodHRwOi8vb2NzcC5jb21vZG9jYS5jb20w
MwYDVR0RBCwwKoIUKi5jb2xsZWN0cml1bWRldi5jb22CEmNvbGxlY3RyaXVtZGV2
LmNvbTANBgkqhkiG9w0BAQsFAAOCAQEAc9ItgvOwsF5NozqlpY48vZU8Ezjcwtmd
5MLfxIssoZ+/WATI1B91nRQk+ZKpanyqGi9+N4QiTsPS8ZWZIQSkkdM9KJpOgenc
8/70TalmFyE4ObXoT0I1GUXMYsP0ujcDDAPhzybGhNRpfMes1X7GrV2iZqo7vfYe
IeVElBzUulPZiDnDK4ptKXAQSO89Ql0O+GLgZf/Lvld6uPQzmydWy/NgxS9gx0ld
ff2+EKYCD8GqO2ExeFmV8bb5PRDzAh568V+vJ3grnAhv4/V2lCo6qQlMVQDjBhLs
PreqXIa4sIQsspBM1IWWH0+X106rGBGmfbiDn8FAxhNqyyMnbN+/yw==
-----END CERTIFICATE-----
"""

CF_SSL_CERT_TEXT = """
-----BEGIN CERTIFICATE-----
MIIE8zCCA9ugAwIBAgIQGfwXF/tjErA57K2133hukjANBgkqhkiG9w0BAQsFADBG
MQswCQYDVQQGEwJVUzEWMBQGA1UEChMNR2VvVHJ1c3QgSW5jLjEfMB0GA1UEAxMW
R2VvVHJ1c3QgU0hBMjU2IFNTTCBDQTAeFw0xNDEwMTYwMDAwMDBaFw0xNjEwMTQy
MzU5NTlaMGkxCzAJBgNVBAYTAlVTMREwDwYDVQQIDAhOZXcgWW9yazERMA8GA1UE
BwwITmV3IFlvcmsxGDAWBgNVBAoMD0NvbGxlY3RyaXVtIExMQzEaMBgGA1UEAwwR
Ki5jb2xsZWN0cml1bS5jb20wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB
AQDNagDb/NTSYp9rhEFKwp+4RbsBbFaqrxC4nyyIu/7qKLjK6aPe7qGyBQI56z43
J292m2EB0wtd/n3Adj2RPfg6ycgll1xeACXWlKwwJDhlL9/8ORtkeGrvcx3ZV9xD
cCcTVUpGYOgiXdEj1n/qJ6b6a/bwh11uswDQb2dLuecWxYW2IvFKamUVBhrqDkU2
j78Tvk2pHWT3ebAGJ3wf8Jcyw8Dl06Vgdo50DquTVrxkIj9rLM2/bE+feVHdtdOO
ExPuj7VDlxXPrxzSGCznY1EdoDqnkvMr/S6i5qJBy6RSQt1o+qhlAn2zxk6K3UB0
7yaEXG6OI4Ntl6NVwpWu5LAjAgMBAAGjggG4MIIBtDAtBgNVHREEJjAkghEqLmNv
bGxlY3RyaXVtLmNvbYIPY29sbGVjdHJpdW0uY29tMAkGA1UdEwQCMAAwDgYDVR0P
AQH/BAQDAgWgMCsGA1UdHwQkMCIwIKAeoByGGmh0dHA6Ly9nai5zeW1jYi5jb20v
Z2ouY3JsMIGhBgNVHSAEgZkwgZYwgZMGCmCGSAGG+EUBBzYwgYQwPwYIKwYBBQUH
AgEWM2h0dHBzOi8vd3d3Lmdlb3RydXN0LmNvbS9yZXNvdXJjZXMvcmVwb3NpdG9y
eS9sZWdhbDBBBggrBgEFBQcCAjA1DDNodHRwczovL3d3dy5nZW90cnVzdC5jb20v
cmVzb3VyY2VzL3JlcG9zaXRvcnkvbGVnYWwwHQYDVR0lBBYwFAYIKwYBBQUHAwEG
CCsGAQUFBwMCMB8GA1UdIwQYMBaAFBRnju2DT9YenUAEDARGoXA0sg9yMFcGCCsG
AQUFBwEBBEswSTAfBggrBgEFBQcwAYYTaHR0cDovL2dqLnN5bWNkLmNvbTAmBggr
BgEFBQcwAoYaaHR0cDovL2dqLnN5bWNiLmNvbS9nai5jcnQwDQYJKoZIhvcNAQEL
BQADggEBAKOXUMgsUfX1qfvI5NcJxPgFPnzvoz3gXpmsMyg8q3wtGPEIeaqRQhdP
2G7ONmGDWxMAZw2s+iGbgMjLX+yh5ymo3t+4ofkEv/FaojuK2k6yN5ccggRNY/va
RFpWKy1VFY4P+ifWfzHS3BQHL+tijYKj8a9/buzU5AhF5i2gVN/217HrH3bu7bgE
BOoUf2EBlSaephm7ERC5CLRHkhYOP6fl7uds098tMWWid9/86K866ba3hh3v3Qyl
kj5VuSw4su6BDhbks/4NSwOsDk667JER+iwR9FEC9u4dxYrc37Kmp26mqRiUS8SB
NgU/vosZfGXwAaWKx/rGBoEG9qm5BZ0=
-----END CERTIFICATE-----
"""



CF_SSL_CERT_DEV_CHAIN = """
-----BEGIN CERTIFICATE-----
MIIGCDCCA/CgAwIBAgIQKy5u6tl1NmwUim7bo3yMBzANBgkqhkiG9w0BAQwFADCB
hTELMAkGA1UEBhMCR0IxGzAZBgNVBAgTEkdyZWF0ZXIgTWFuY2hlc3RlcjEQMA4G
A1UEBxMHU2FsZm9yZDEaMBgGA1UEChMRQ09NT0RPIENBIExpbWl0ZWQxKzApBgNV
BAMTIkNPTU9ETyBSU0EgQ2VydGlmaWNhdGlvbiBBdXRob3JpdHkwHhcNMTQwMjEy
MDAwMDAwWhcNMjkwMjExMjM1OTU5WjCBkDELMAkGA1UEBhMCR0IxGzAZBgNVBAgT
EkdyZWF0ZXIgTWFuY2hlc3RlcjEQMA4GA1UEBxMHU2FsZm9yZDEaMBgGA1UEChMR
Q09NT0RPIENBIExpbWl0ZWQxNjA0BgNVBAMTLUNPTU9ETyBSU0EgRG9tYWluIFZh
bGlkYXRpb24gU2VjdXJlIFNlcnZlciBDQTCCASIwDQYJKoZIhvcNAQEBBQADggEP
ADCCAQoCggEBAI7CAhnhoFmk6zg1jSz9AdDTScBkxwtiBUUWOqigwAwCfx3M28Sh
bXcDow+G+eMGnD4LgYqbSRutA776S9uMIO3Vzl5ljj4Nr0zCsLdFXlIvNN5IJGS0
Qa4Al/e+Z96e0HqnU4A7fK31llVvl0cKfIWLIpeNs4TgllfQcBhglo/uLQeTnaG6
ytHNe+nEKpooIZFNb5JPJaXyejXdJtxGpdCsWTWM/06RQ1A/WZMebFEh7lgUq/51
UHg+TLAchhP6a5i84DuUHoVS3AOTJBhuyydRReZw3iVDpA3hSqXttn7IzW3uLh0n
c13cRTCAquOyQQuvvUSH2rnlG51/ruWFgqUCAwEAAaOCAWUwggFhMB8GA1UdIwQY
MBaAFLuvfgI9+qbxPISOre44mOzZMjLUMB0GA1UdDgQWBBSQr2o6lFoL2JDqElZz
30O0Oija5zAOBgNVHQ8BAf8EBAMCAYYwEgYDVR0TAQH/BAgwBgEB/wIBADAdBgNV
HSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwGwYDVR0gBBQwEjAGBgRVHSAAMAgG
BmeBDAECATBMBgNVHR8ERTBDMEGgP6A9hjtodHRwOi8vY3JsLmNvbW9kb2NhLmNv
bS9DT01PRE9SU0FDZXJ0aWZpY2F0aW9uQXV0aG9yaXR5LmNybDBxBggrBgEFBQcB
AQRlMGMwOwYIKwYBBQUHMAKGL2h0dHA6Ly9jcnQuY29tb2RvY2EuY29tL0NPTU9E
T1JTQUFkZFRydXN0Q0EuY3J0MCQGCCsGAQUFBzABhhhodHRwOi8vb2NzcC5jb21v
ZG9jYS5jb20wDQYJKoZIhvcNAQEMBQADggIBAE4rdk+SHGI2ibp3wScF9BzWRJ2p
mj6q1WZmAT7qSeaiNbz69t2Vjpk1mA42GHWx3d1Qcnyu3HeIzg/3kCDKo2cuH1Z/
e+FE6kKVxF0NAVBGFfKBiVlsit2M8RKhjTpCipj4SzR7JzsItG8kO3KdY3RYPBps
P0/HEZrIqPW1N+8QRcZs2eBelSaz662jue5/DJpmNXMyYE7l3YphLG5SEXdoltMY
dVEVABt0iN3hxzgEQyjpFv3ZBdRdRydg1vs4O2xyopT4Qhrf7W8GjEXCBgCq5Ojc
2bXhc3js9iPc0d1sjhqPpepUfJa3w/5Vjo1JXvxku88+vZbrac2/4EjxYoIQ5QxG
V/Iz2tDIY+3GH5QFlkoakdH368+PUq4NCNk+qKBR6cGHdNXJ93SrLlP7u3r7l+L4
HyaPs9Kg4DdbKDsx5Q5XLVq4rXmsXiBmGqW5prU5wfWYQ//u+aen/e7KJD2AFsQX
j4rBYKEMrltDR5FL1ZoXX/nUh8HCjLfn4g8wGTeGrODcQgPmlKidrv0PJFGUzpII
0fxQ8ANAe4hZ7Q7drNJ3gjTcBpUC2JD5Leo31Rpg0Gcg19hCC0Wvgmje3WYkN5Ap
lBlGGSW4gNfL1IYoakRwJiNiqZ+Gb7+6kHDSVneFeO/qJakXzlByjAA6quPbYzSf
+AZxAeKCINT+b72x
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIIFdDCCBFygAwIBAgIQJ2buVutJ846r13Ci/ITeIjANBgkqhkiG9w0BAQwFADBv
MQswCQYDVQQGEwJTRTEUMBIGA1UEChMLQWRkVHJ1c3QgQUIxJjAkBgNVBAsTHUFk
ZFRydXN0IEV4dGVybmFsIFRUUCBOZXR3b3JrMSIwIAYDVQQDExlBZGRUcnVzdCBF
eHRlcm5hbCBDQSBSb290MB4XDTAwMDUzMDEwNDgzOFoXDTIwMDUzMDEwNDgzOFow
gYUxCzAJBgNVBAYTAkdCMRswGQYDVQQIExJHcmVhdGVyIE1hbmNoZXN0ZXIxEDAO
BgNVBAcTB1NhbGZvcmQxGjAYBgNVBAoTEUNPTU9ETyBDQSBMaW1pdGVkMSswKQYD
VQQDEyJDT01PRE8gUlNBIENlcnRpZmljYXRpb24gQXV0aG9yaXR5MIICIjANBgkq
hkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAkehUktIKVrGsDSTdxc9EZ3SZKzejfSNw
AHG8U9/E+ioSj0t/EFa9n3Byt2F/yUsPF6c947AEYe7/EZfH9IY+Cvo+XPmT5jR6
2RRr55yzhaCCenavcZDX7P0N+pxs+t+wgvQUfvm+xKYvT3+Zf7X8Z0NyvQwA1onr
ayzT7Y+YHBSrfuXjbvzYqOSSJNpDa2K4Vf3qwbxstovzDo2a5JtsaZn4eEgwRdWt
4Q08RWD8MpZRJ7xnw8outmvqRsfHIKCxH2XeSAi6pE6p8oNGN4Tr6MyBSENnTnIq
m1y9TBsoilwie7SrmNnu4FGDwwlGTm0+mfqVF9p8M1dBPI1R7Qu2XK8sYxrfV8g/
vOldxJuvRZnio1oktLqpVj3Pb6r/SVi+8Kj/9Lit6Tf7urj0Czr56ENCHonYhMsT
8dm74YlguIwoVqwUHZwK53Hrzw7dPamWoUi9PPevtQ0iTMARgexWO/bTouJbt7IE
IlKVgJNp6I5MZfGRAy1wdALqi2cVKWlSArvX31BqVUa/oKMoYX9w0MOiqiwhqkfO
KJwGRXa/ghgntNWutMtQ5mv0TIZxMOmm3xaG4Nj/QN370EKIf6MzOi5cHkERgWPO
GHFrK+ymircxXDpqR+DDeVnWIBqv8mqYqnK8V0rSS527EPywTEHl7R09XiidnMy/
s1Hap0flhFMCAwEAAaOB9DCB8TAfBgNVHSMEGDAWgBStvZh6NLQm9/rEJlTvA73g
JMtUGjAdBgNVHQ4EFgQUu69+Aj36pvE8hI6t7jiY7NkyMtQwDgYDVR0PAQH/BAQD
AgGGMA8GA1UdEwEB/wQFMAMBAf8wEQYDVR0gBAowCDAGBgRVHSAAMEQGA1UdHwQ9
MDswOaA3oDWGM2h0dHA6Ly9jcmwudXNlcnRydXN0LmNvbS9BZGRUcnVzdEV4dGVy
bmFsQ0FSb290LmNybDA1BggrBgEFBQcBAQQpMCcwJQYIKwYBBQUHMAGGGWh0dHA6
Ly9vY3NwLnVzZXJ0cnVzdC5jb20wDQYJKoZIhvcNAQEMBQADggEBAGS/g/FfmoXQ
zbihKVcN6Fr30ek+8nYEbvFScLsePP9NDXRqzIGCJdPDoCpdTPW6i6FtxFQJdcfj
Jw5dhHk3QBN39bSsHNA7qxcS1u80GH4r6XnTq1dFDK8o+tDb5VCViLvfhVdpfZLY
Uspzgb8c8+a4bmYRBbMelC1/kZWSWfFMzqORcUx8Rww7Cxn2obFshj5cqsQugsv5
B5a6SE2Q8pTIqXOi6wZ7I53eovNNVZ96YUWYGGjHXkBrI/V5eu+MtWuLt29G9Hvx
PUsE2JOAWVrgQSQdso8VYFhH2+9uRv0V9dlfmrPb2LjkQLPNlzmuhbsdjrzch5vR
pu/xO28QOG8=
-----END CERTIFICATE-----
"""

CF_SSL_CERT_CHAIN = """
-----BEGIN CERTIFICATE-----
MIIExzCCA6+gAwIBAgIQQYISfRLZxrMhOUMSVmQAuDANBgkqhkiG9w0BAQsFADCB
mDELMAkGA1UEBhMCVVMxFjAUBgNVBAoTDUdlb1RydXN0IEluYy4xOTA3BgNVBAsT
MChjKSAyMDA4IEdlb1RydXN0IEluYy4gLSBGb3IgYXV0aG9yaXplZCB1c2Ugb25s
eTE2MDQGA1UEAxMtR2VvVHJ1c3QgUHJpbWFyeSBDZXJ0aWZpY2F0aW9uIEF1dGhv
cml0eSAtIEczMB4XDTEzMDUyMzAwMDAwMFoXDTIzMDUyMjIzNTk1OVowRjELMAkG
A1UEBhMCVVMxFjAUBgNVBAoTDUdlb1RydXN0IEluYy4xHzAdBgNVBAMTFkdlb1Ry
dXN0IFNIQTI1NiBTU0wgQ0EwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB
AQDGqQtdF6V9xs8q78Zm0UIeX4N4aJGv5qeL8B1EAQoZypzUix3hoZCjwVu011tq
i/wOSR7CYin+gBU5i4EqJ7X7EqgFIgvFLPXZmN0WLztm52KiQzKsj7WFyFIGLFzA
d/pn94PoXgWNyKuhFjKK0kDshjocI6mNtQDecr2FVf4GAWBdrbPgZXOlkhSelFZv
k+6vqTowJUqOCYTvt9LV15tJzenAXmdxIqxQkEMgXaGjFYP9/Kc5vGtlSBJg/90j
szqq9J+cN1NBokeTgTMJ5SLGyBxJoW6NzIOzms3qQ/IZ0yTLqCmuUsz0CCewhOrO
J7XhNBNzklyHhirGsGg2rcsJAgMBAAGjggFcMIIBWDA7BggrBgEFBQcBAQQvMC0w
KwYIKwYBBQUHMAGGH2h0dHA6Ly9wY2EtZzMtb2NzcC5nZW90cnVzdC5jb20wEgYD
VR0TAQH/BAgwBgEB/wIBADBMBgNVHSAERTBDMEEGCmCGSAGG+EUBBzYwMzAxBggr
BgEFBQcCARYlaHR0cDovL3d3dy5nZW90cnVzdC5jb20vcmVzb3VyY2VzL2NwczA7
BgNVHR8ENDAyMDCgLqAshipodHRwOi8vY3JsLmdlb3RydXN0LmNvbS9HZW9UcnVz
dFBDQS1HMy5jcmwwDgYDVR0PAQH/BAQDAgEGMCoGA1UdEQQjMCGkHzAdMRswGQYD
VQQDExJWZXJpU2lnbk1QS0ktMi00MTYwHQYDVR0OBBYEFBRnju2DT9YenUAEDARG
oXA0sg9yMB8GA1UdIwQYMBaAFMR5yo6hTgMdHNxr2zFblD4/MH8tMA0GCSqGSIb3
DQEBCwUAA4IBAQAQEOryENYIRuLBjz42WcgrD/5N7OP4tlYxeCXUdvII3e8/zYsc
fqp//AuoI2RRs4fWCfoi+scKUejOuPYDcOAbWrmxspMREPmXBQcpbG1XJVTo+Wab
Dvvbn+6Wb2XLH9hVzjH6zwL00H9QZv8veZulwt/Wz8gVg5aEmLJG1F8TqD6nNJwF
ONrP1mmVqSaHdgHXslEPgWlGJhyZtoNY4ztYj9y0ccC5v0KcHAOe5Eao6rnBzfZb
qTyW+3mkM3Onnni5cNxydMQyyAAbye9I0/s6m/r+eppAaRzI2ig3C9OjuX6WzCso
w1Zsb+nbUrH6mvvnr7WXpiLDxaiTsQDJB7J9
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIID/jCCAuagAwIBAgIQFaxulBmyeUtB9iepwxgPHzANBgkqhkiG9w0BAQsFADCB
mDELMAkGA1UEBhMCVVMxFjAUBgNVBAoTDUdlb1RydXN0IEluYy4xOTA3BgNVBAsT
MChjKSAyMDA4IEdlb1RydXN0IEluYy4gLSBGb3IgYXV0aG9yaXplZCB1c2Ugb25s
eTE2MDQGA1UEAxMtR2VvVHJ1c3QgUHJpbWFyeSBDZXJ0aWZpY2F0aW9uIEF1dGhv
cml0eSAtIEczMB4XDTA4MDQwMjAwMDAwMFoXDTM3MTIwMTIzNTk1OVowgZgxCzAJ
BgNVBAYTAlVTMRYwFAYDVQQKEw1HZW9UcnVzdCBJbmMuMTkwNwYDVQQLEzAoYykg
MjAwOCBHZW9UcnVzdCBJbmMuIC0gRm9yIGF1dGhvcml6ZWQgdXNlIG9ubHkxNjA0
BgNVBAMTLUdlb1RydXN0IFByaW1hcnkgQ2VydGlmaWNhdGlvbiBBdXRob3JpdHkg
LSBHMzCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBANziXmJYHTNXOTIz
+uvLh4yn1ErdBojqZI4xmKU4kB6Yzy5jK/BGvESyiaHAKAxJcCGVn2TAppMSAmUm
hsalifD614SgcK9PGpc/BkTVyetyEH3kMSj7HGHmKAdEc5IiaacDiGydY8hS2pgn
5whMcD60yRLBxWeDXTPzAxHsatBT4tG6NmCUgLthY2xbF37fQJQeqw3CIShwiP/W
JmxsYAQlTlV+fe+/lEjetx3dcI0FX4ilm/LC7urRQEFtYjgdVgbFA0dRIBn8exAL
DmKudlW/X3e+PkkBUz2YJQN2JFodtNuJ6nnltrM7P7pMKEF/BqxqjsHQ9gUdfeZC
huOl1UcCAwEAAaNCMEAwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAQYw
HQYDVR0OBBYEFMR5yo6hTgMdHNxr2zFblD4/MH8tMA0GCSqGSIb3DQEBCwUAA4IB
AQAtxRPPVoB7eni9n64smefv2t+UXglpp+duaIy9cr5HqQ6XErhK8WTTOd8lNNTB
zU6B8A8ExCSzNJbGpqow32hhc9f5joWJ7w5elShKKiePEI4ufIbEAp7aDHdlDkQN
kv39sxY2+hENHYwOB4lqKVb3cvTdFZx3NWZXqxNT2I7BQMXXExZacse3aQHEerGD
AWh9jUGhlBjBJVz88P6DAod8DQ3PLghcSkANPuyBYeYk28rgDi0Hsj5W3I31QYUH
SJsMC8tJP33st/3LjWeJGqvtux6jAAgIFyqCXDFdRootD4abdNlF+9RAsXqqaC2G
spki4cErx5z481+oghLrGREt
-----END CERTIFICATE-----
"""
