POSTGRESQL_DBNAME = "new_deploy"
POSTGRESQL_HOST = 'localhost'
POSTGRESQL_PORT = '5432'
POSTGRESQL_USERNAME = 'postgres'
POSTGRESQL_PASSWORD = 'postgres'
POSTGRESQL_ECHO_MODE = False

aws_access_key_id = ""
aws_secret_access_key = ""

SLACK_URL = "https://hooks.slack.com/services/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"

FRONTEND_SETTINGS_KEYS = (
    "APP.AVIARY.apiKey",
    "APP.FILES_TYPES.documents.url",
    "APP.FILES_TYPES.images.updateImageUrl",
    "APP.FILES_TYPES.images.url",
    "APP.GA_KEY",
    "APP.GTM_ENABLED",
    "APP.GTM_KEY",
    "APP.GTM_TRACK_ERRORS",
    "APP.GTM_TRACK_EVENTS",
    "APP.GTM_TRACK_PAGE_VIEW",
    "APP.INSPECTLET_WID",
    "APP.MAP_ID",
    "APP.MAP_MARKER_ICON_URL",
    "APP.MAP_PK",
    "APP.MAP_TILES_URL",
    "APP.PRIVATE_SALES_ADDRESS",
    "APP.ROLLBAL_ENABLED",
    "APP.SIGN_IN_ADDRESS",
    "APP.SIGN_OUT_ADDRESS",
    "APP.SOCKET_ADDRESS",
    "APP.SPEED_OF_ME_ACCOUNT",
    "APP.SPEED_OF_ME_DOMAIN",
    "APP.SPEED_OF_ME_MIN_SPEED",
    "APP.SPEED_OF_ME_TIME",
    "APP.TERMS_AND_CONDITIONS_ADDRESS",
    "APP.TRANSLATIONS_ADDRESS",
    "APP.saveFileUrlsUrl",
    "APP.FILES_TYPES.contacts.url",
    "EMBER_LOG_VERSION",
    "ENABLE_SOURCEMAPS",
    "MINIFY_CSS",
    "MINIFY_JS",
    ("APP.COOKIES_PREFIX", "COOKIES_PREFIX"),
    ("APP.ROLLBAR_ENV", "ROLLBAR_ENV"),
    ("APP.ROLLBAR_KEY", "ROLLBAR_KEY"),
    "ember-cli-mirage.enabled",
    "APP.API_HOST",
    "APP.GAVEL_ADDRESS",
    "APP.SUPPORT_ADDRESS",
    "APP.PARTNER_CONFIGS_BUCKET",
    "APP.RECURLY_PUBLIC_KEY",
    ("APP.DEBUG", "DEBUG"),
)


PRIVATE_SALES_SETTINGS_KEYS = (
    "APP.SIGN_OUT_ADDRESS",
    "APP.TRANSLATIONS_ADDRESS",
    "APP.SOCKET_ADDRESS",
    "APP.FILES_TYPES.documents.url",
    "APP.TRANSLATIONS_ADDRESS",
    "APP.API_HOST",
    "MINIFY_CSS",
    "MINIFY_JS",
)

AUTH_SETTINGS_KEYS = (
    "APP.RECURLY_MAX_PLANS_COUNT",
    "APP.APP_ADDRESS",
    "APP.SIGN_UP_DATA_IMPORT_VALIDATE_URL",
    "APP.SIGN_UP_DATA_IMPORT_STATUS",
    "APP.FORGOT_PASSWORD_URL",
    "APP.GA_KEY",
    "APP.GTM_ENABLED",
    "APP.GTM_KEY",
    "APP.GTM_TRACK_ERRORS",
    "APP.GTM_TRACK_EVENTS",
    "APP.GTM_TRACK_PAGE_VIEW",
    "APP.INSPECTLET_WID",
    "APP.RECURLY_PLANS",
    "APP.RECURLY_PUBLIC_KEY",
    "APP.RESET_PASSWORD_URL",
    "APP.SIGN_IN_URL",
    "APP.SIGN_OUT_URL",
    "APP.SIGN_UP_BY_EMAIL_URL",
    "APP.SIGN_UP_DATA_IMPORT_STATUS",
    "APP.SIGN_UP_DATA_IMPORT_VALIDATE_URL",
    "APP.SIGN_UP_URL",
    "APP.SIGN_UP_VALIDATE_URL",
    "APP.SOCKET_ADDRESS",
    "APP.API_HOST",
    "APP.PARTNER_CONFIGS_BUCKET",
    "ENABLE_SOURCEMAPS",
    "MINIFY_CSS",
    "MINIFY_JS",
    ("APP.COOKIES_PREFIX", "COOKIES_PREFIX"),
    ("APP.ROLLBAR_ENV", "ROLLBAR_ENV"),
    ("APP.ROLLBAR_KEY", "ROLLBAR_KEY"),
    "APP.OAUTH_GRANT_URL",
    "APP.TRANSLATIONS_ADDRESS",
)

APPS_SETTINGS_MAPPING = {
    "frontend": FRONTEND_SETTINGS_KEYS,
    "auth": AUTH_SETTINGS_KEYS,
    "pvr": PRIVATE_SALES_SETTINGS_KEYS
}


UPPER_TO_LOWER_SETTINGS_MAPPINGS = {
    "DEBUG": "debug",
    "ROLLBAR_ENV": "rollbar_env",
    "ROLLBAR_KEY": "rollbar_key",
    "COOKIES_PREFIX": "cookies_prefix",
    "APP.AVIARY.apiKey": "aviary_key",
    "APP.FILES_TYPES.documents.url": ("img", "app", lambda x, y: "https://{}/document/?token={}".format(x, '{{TOKEN}}') if y == "pvr" else "https://{}/document/".format(x)),
    "APP.FILES_TYPES.images.updateImageUrl": ("img", lambda x: "https://{}/image_update".format(x)),
    "APP.FILES_TYPES.images.url": ("img", lambda x: "https://{}/image/".format(x)),
    "APP.GA_KEY": "ga_key",
    "APP.GTM_ENABLED": "gtm_enabled",
    "APP.GTM_KEY": "gtm_key",
    "APP.GTM_TRACK_ERRORS": "gtm_track_errors",
    "APP.GTM_TRACK_EVENTS": "gtm_track_events",
    "APP.GTM_TRACK_PAGE_VIEW": "gtm_track_page_view",
    "APP.INSPECTLET_WID": "inspectlet_id",
    "APP.MAP_ID": "mapbox_id",
    "APP.MAP_PK": "mapbox_key",
    "APP.PRIVATE_SALES_ADDRESS": ("pvr", lambda x: "https://{}".format(x)),
    "APP.ROLLBAL_ENABLED": "log_to_rollbar",
    "APP.SIGN_IN_ADDRESS": ("auth", "app", lambda x, y : "https://{}/sign-in?app=gavel".format(x) if y == "gavel" else "https://{}/sign-in".format(x)),
    "APP.SIGN_OUT_ADDRESS": ("auth", lambda x: "https://{}/sign-out".format(x)),
    "APP.SOCKET_ADDRESS": ("api", lambda x: "https://{}".format(x)),
    "APP.SPEED_OF_ME_ACCOUNT": "speed_of_me_account",
    "APP.SPEED_OF_ME_DOMAIN": "speed_of_me_domain",
    "APP.SPEED_OF_ME_MIN_SPEED": "speed_of_me_min_speed",
    "APP.SPEED_OF_ME_TIME": "speed_of_me_time",
    "APP.TERMS_AND_CONDITIONS_ADDRESS": "terms_and_condition_url",
    "APP.TRANSLATIONS_ADDRESS": ("api", "translations_version", lambda x, y: "https://{}/translations/{}/".format(x, y)),
    "APP.saveFileUrlsUrl": ("api", lambda x: "https://{}/contact-import".format(x)),
    "APP.FILES_TYPES.contacts.url": ("img", lambda x: "https://{}/document".format(x)),
    "EMBER_LOG_VERSION": "debug",
    "ENABLE_SOURCEMAPS": "debug",
    "MINIFY_CSS": "minify_css",
    "MINIFY_JS": "minify_js",
    "APP.MAP_MARKER_ICON_URL": "map_marker_icon_url",
    "APP.MAP_TILES_URL": "map_titles_url",
    "ember-cli-mirage.enabled": "ember_cli_mirage",
    "APP.API_HOST": ("api_v6", "aws_api_gateway_version", "gavel_domain_name", "domain_name", "app",
                     lambda x, y, n, c, z: "https://{}.{}".format(n, c) if z == "gavel" else {
                         "frontend": "https://{}/{}",
                         "admin_tool": "{}/{}",
                         "auth": "https://{}/{}",
                         "pvr": "https://{}/{}",
                     }.get(z).format(x, y)),
    "APP.ES_API_HOST": ("gavel_domain_name", "domain_name", "aws_api_gateway_version", lambda x, y, z: "{}.{}/{}/gavel".format(x, y, z)),
    "APP.RECURLY_MAX_PLANS_COUNT": "recurly_max_plans_count",
    "APP.APP_ADDRESS": ("frontend", lambda x: "https://{}".format(x)),
    "APP.SIGN_UP_DATA_IMPORT_VALIDATE_URL": ("api", lambda x: "https://{}/activate_account/".format(x)),
    "APP.SIGN_UP_DATA_IMPORT_STATUS": ("api", lambda x: "https://{}/get_migration_status/".format(x)),
    "APP.FORGOT_PASSWORD_URL": ("api", lambda x: "https://{}/forgot_password/".format(x)),
    "APP.RECURLY_PLANS": "recurly_plans",
    "APP.RECURLY_PUBLIC_KEY": "recurly_public_key",
    "APP.RESET_PASSWORD_URL": ("api", lambda x: "https://{}/reset_password/".format(x)),
    "APP.SIGN_IN_URL": ("api", lambda x: "https://{}/signin/".format(x)),
    "APP.SIGN_OUT_URL": ("api", lambda x: "https://{}/signout/".format(x)),
    "APP.SIGN_UP_BY_EMAIL_URL": ("api", lambda x: "https://{}/signup_by_invite/".format(x)),
    "APP.SIGN_UP_URL": ("api", lambda x: "https://{}/signup/".format(x)),
    "APP.SIGN_UP_VALIDATE_URL": ("api", lambda x: "https://{}/validate_signup/".format(x)),
    "APP.ROLLBAR_KEY": "rollbar_key",
    "IMAGE_PROCESSING_DOMAIN": ("img", lambda x: "https://{}".format(x)),
    "APP.SUPPORT_ADDRESS": "support_address",
    "APP.PARTNER_CONFIGS_BUCKET": "partner_configs_bucket",
}

AWS_S3_KEYS = (
    "aws_s3_key",
    "aws_s3_secret_key",
    "aws_s3_bucket_name",
    "aws_s3_region",
)
